# Generated by Django 4.2.5 on 2023-10-01 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=900, null=True)),
                ('download_url', models.CharField(blank=True, max_length=900, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=900, null=True)),
                ('source_url', models.CharField(blank=True, max_length=900, null=True)),
                ('screenshots', models.JSONField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
