# Generated by Django 4.2.5 on 2023-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='upload_source_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
