# Generated by Django 4.2.5 on 2023-10-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0004_sourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiApp.sourcetype'),
        ),
    ]
