# Generated by Django 4.2.5 on 2023-10-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0006_errorbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorBase',
        ),
    ]
