# Generated by Django 4.2.5 on 2023-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0007_delete_errorbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
