# Generated by Django 4.2.5 on 2023-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0008_movieinfo_file_id_movieinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cyber_access_token', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
