# Generated by Django 4.2.5 on 2023-10-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0010_cyberuser_account_id_movieinfo_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='imdb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
