# Generated by Django 4.2.5 on 2023-10-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0011_movieinfo_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberuser',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiApp.sourcetype'),
        ),
    ]
