# Generated by Django 4.2.5 on 2023-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0013_alter_movieinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
