# Generated by Django 4.2.5 on 2023-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0014_alter_movieinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='episode',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='is_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
