# Generated by Django 4.2.5 on 2023-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0015_movieinfo_episode_movieinfo_is_web_movieinfo_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='season',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
