# Generated by Django 4.2.5 on 2023-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0016_alter_movieinfo_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberuser',
            name='is_web_account',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
