# Generated by Django 4.2.5 on 2023-10-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0017_cyberuser_is_web_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberuser',
            name='is_web_account',
            field=models.BooleanField(default=False),
        ),
    ]
