# Generated by Django 4.2.5 on 2023-11-08 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0021_rename_user_id_report_download_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='last_login_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
