# Generated by Django 4.2.5 on 2023-11-08 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0022_report_first_login_date_report_last_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='first_login_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
