# Generated by Django 4.2.5 on 2023-11-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0023_alter_report_first_login_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='download_user',
            new_name='device_id',
        ),
    ]
