# Generated by Django 4.2.5 on 2023-11-08 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0024_rename_download_user_report_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiApp.appinfo'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='language',
            field=models.CharField(blank=True, default='Hindi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 1, 35, 56, 276189), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 1, 35, 56, 276189), null=True),
        ),
    ]
