# Generated by Django 4.2.5 on 2024-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0027_alter_movieinfo_slug_alter_movieinfo_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='static_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
