# Generated by Django 4.2.5 on 2024-05-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0028_movieinfo_category_movieinfo_static_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='category',
            new_name='industry',
        ),
    ]
