# Generated by Django 4.2.5 on 2024-05-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0029_rename_category_movieinfo_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='all_episode',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
